### ISSUE TITLE
there is no SLM related code?

### ISSUE THREAD

**Issue by hhy150** [mayubo2333/LLM-IE#4]
Hello, thank you very much for being able to open source code!!! But it seems that there is no SLM related code provided here, I wonder if it can be provided?

**Comment by mayubo2333** [comment]
Thanks for your interest on our work. I can consider to release SLM related code later but there is no clear timeline for it in the near future (I'm a little busy recently).

From my understanding, it will not take your much time to write your own SLM related code because SLM methods used are classical ones (like vanilla fine-tuning, FSLS and KnowPrompt). I highly recommend you to implement these method by your own and then save the predictions as the format examples shown in `./SLM_results` before using LLM reranking.

**Comment by mayubo2333** [comment]
> Hello, thank you very much for being able to open source code!!! But it seems that there is no SLM related code provided here, I wonder if it can be provided?

Thanks for your interest on our work. I can consider to release SLM related code later but there is no clear timeline for it in the near future (I'm a little busy recently).

From my understanding, it will not take your much time to write your own SLM related code because SLM methods used are classical ones (like vanilla fine-tuning, FSLS and KnowPrompt). I highly recommend you to implement these method by your own and then save the predictions as the format examples shown in ./SLM_results before using LLM reranking.

**Comment by hhy150** [comment]
Thank you for your reply. You make sense. I can run an SLM model myself, so there is no need to provide any more code. Thank you!
