### ISSUE TITLE
Details of Few-shot IE Datasets

### ISSUE THREAD

**Issue by joe-xj** [mayubo2333/LLM-IE#7]
Dear author
Thank u for your code.

In your article's Appendix _**A.2 Details of Few-shot IE Datasets**_, you mentioned the segmentation of various datasets in the few-shot environment. We are very interested in the code for how to segment the datasets. Could you please make it public? This would be helpful for the IE community to unify and develop in the few-shot context. Thank you very much!

**Comment by mayubo2333** [comment]
> Dear author Thank u for your code.
> 
> In your article's Appendix _**A.2 Details of Few-shot IE Datasets**_, you mentioned the segmentation of various datasets in the few-shot environment. We are very interested in the code for how to segment the datasets. Could you please make it public? This would be helpful for the IE community to unify and develop in the few-shot context. Thank you very much!

Thanks for your interest for our work.
Add it to my to-do list, but sorry no specific date can be promised.

For quick use, you can refer to `https://github.com/mayubo2333/fewshot_ED/tree/main/dataset_processing`. I remember data preprocessing code is developed based on this previous work. You can use this code to segment the ED dataset (and with tiny modification, it is compatible for NER dataset as well since they share the same format).

**Comment by joe-xj** [comment]
Thanks, Ifound it, and It's very helpful.
